/**
 * AI Provider Abstraction Placeholder
 * This will be implemented in Slice 6 (AI Section Draft).
 */
export interface AIProvider {
  generateDraft(prompt: string, schema: any): Promise<any>;
}

export class MockAIProvider implements AIProvider {
  async generateDraft(prompt: string, schema: any): Promise<any> {
    return {
      content: "This is a mock draft generated by the AI.",
      confidence: "medium",
    };
  }
}
